#!/bin/bash
# Assumes that the environment variable UNISON_DIR is set to the top of the
# Unison repo
MULTIBACKEND_DIR=$UNISON_DIR/src/solvers/multi_backend
MINIZINC_DIR=$MULTIBACKEND_DIR/minizinc
COMMON_DIR=$MULTIBACKEND_DIR/common
search='topdown.mzn'
allsolns='-a'
mzn='mzn-gecode'
cumulative='false'
ncores='1'
statflag='-s'
toprefix='-time '
toflag=''
freeflag=''
while [ $# -gt  1 ]; do
    opt="$1"
    shift
    case "${opt}" in
      --bottomup | --bottom-up | --bottom_up)
        search='bottomup.mzn'
        allsolns=''
      ;;
      --topdown | --top-down | --top_down)
        search='topdown.mzn'
        allsolns='-a'
      ;;
      --gecode)
        mzn='mzn-gecode'
        cumulative='true'
      ;;
      --sicstus)
        mzn='mzn-sicstus'
        cumulative='true'
      ;;
      --g12cpx)
        mzn='mzn-g12cpx'
        cumulative='false'
      ;;
      --cpx)
        mzn='mzn-cpx'
        cumulative='false'
      ;;
      --chuffed)
        mzn='mzn-chuffed'
        cumulative='false'
        statflag='--fzn-flag -verbosity=3'
	toprefix='-time_out='
      ;;
      --cumulative)
        cumulative='true'
      ;;
      --no-cumulative)
        cumulative='false'
      ;;
      --free)
        freeflag='--fzn-flag -f'
      ;;
      --vsids)
        freeflag='--fzn-flag -vsids=true'
      ;;
      --to)
	toflag='--fzn-flag '$toprefix$1
	shift
      ;;
      -o)
	OUTJSON=$1
	shift
      ;;
      -p)
	ncores=$1
	shift
      ;;
    esac
done
BASENAME=$(basename $1 .ext.json)
DIRBASENAME=${1%.ext.json}
EXTJSON=$1
shift
echo "json2dzn('${EXTJSON}')." | sicstus -f --nologo --noinfo -l $MINIZINC_DIR/model2dzn.pl
cat $MINIZINC_DIR/code-generation.mzn $MINIZINC_DIR/${search} > code-generation.mzn
if [ $mzn = 'mzn-gecode' ]; then
  pflag='-p'
  pvalue=${ncores}
else
  pflag=''
  pvalue=''
fi
echo ${mzn} -k ${statflag} ${pflag} ${pvalue} ${freeflag} ${toflag} ${allsolns} --no-optimize -D good_cumulative=${cumulative} code-generation.mzn $DIRBASENAME.dzn | $COMMON_DIR/outfilter.pl > ${OUTJSON}
time ${mzn} -k ${statflag} ${pflag} ${pvalue} ${freeflag} ${toflag} ${allsolns} --no-optimize -D good_cumulative=${cumulative} code-generation.mzn $DIRBASENAME.dzn | $COMMON_DIR/outfilter.pl > ${OUTJSON}
